arrowParens: avoid
useTabs: true
tabWidth: 4
singleQuote: true
semi: false
printWidth: 100
trailingComma: all
overrides:
  - files:
      - '*.md'
      - '*.json'
      - '*.yaml'
      - '*.yml'
    options:
      useTabs: false
      tabWidth: 2
svelteSortOrder: scripts-markup-styles
svelteBracketNewLine: true
